on:
  push:
    branches: [ master ]
name: 🚀 Deploy website on push with minify
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

#      - name: Minify Action
#        uses: anthonyftwang/minify-action@v1.0.1

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          exclude: '[**/.git*, **/.git*/**, **/node_modules/**, deploy_localhost.*, README.md, **/docs/**, **/test/**, **/sql/**, LICENSE]'
          server-dir: producto-desayuno/
